name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build
      - name: Generate JaCoCo Badge Unit Test
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          coverage-badge-filename: jacoco-unit.svg
          branches-badge-filename: branches-unit.svg
          jacoco-csv-file: app/build/reports/jacoco/test/jacocoTestReport.csv
      - name: Generate JaCoCo Badge Component Test
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          coverage-badge-filename: jacoco-component.svg
          branches-badge-filename: branches-component.svg
          jacoco-csv-file: test/build/reports/jacoco/test/jacocoTestReport.csv
